const kanaList = [
    { id: 1, row: 'a', rowName: 'あ行', romanic: 'a', hiragana: 'あ', katakana: 'ア', time: 13.80 },
    { id: 2, row: 'a', rowName: 'あ行', romanic: 'i', hiragana: 'い', katakana: 'イ', time: 14.68 },
    { id: 3, row: 'a', rowName: 'あ行', romanic: 'u', hiragana: 'う', katakana: 'ウ', time: 16.45 },
    { id: 4, row: 'a', rowName: 'あ行', romanic: 'e', hiragana: 'え', katakana: 'エ', time: 17.50 },
    { id: 5, row: 'a', rowName: 'あ行', romanic: 'o', hiragana: 'お', katakana: 'オ', time: 19.00 },
    { id: 6, row: 'ka', rowName: 'か行', romanic: 'ka', hiragana: 'か', katakana: 'カ', time: 21.40 },
    { id: 7, row: 'ka', rowName: 'か行', romanic: 'ki', hiragana: 'き', katakana: 'キ', time: 22.60 },
    { id: 8, row: 'ka', rowName: 'か行', romanic: 'ku', hiragana: 'く', katakana: 'ク', time: 23.90 },
    { id: 9, row: 'ka', rowName: 'か行', romanic: 'ke', hiragana: 'け', katakana: 'ケ', time: 25.00 },
    { id: 10, row: 'ka', rowName: 'か行', romanic: 'ko', hiragana: 'こ', katakana: 'コ', time: 26.30 },
    { id: 11, row: 'sa', rowName: 'さ行', romanic: 'sa', hiragana: 'さ', katakana: 'サ', time: 28.50 },
    { id: 12, row: 'sa', rowName: 'さ行', romanic: 'shi', hiragana: 'し', katakana: 'シ', time: 29.45 },
    { id: 13, row: 'sa', rowName: 'さ行', romanic: 'su', hiragana: 'す', katakana: 'ス', time: 30.80 },
    { id: 14, row: 'sa', rowName: 'さ行', romanic: 'se', hiragana: 'せ', katakana: 'セ', time: 32.00 },
    { id: 15, row: 'sa', rowName: 'さ行', romanic: 'so', hiragana: 'そ', katakana: 'ソ', time: 33.00 },
    { id: 16, row: 'ta', rowName: 'た行', romanic: 'ta', hiragana: 'た', katakana: 'タ', time: 35.00 },
    { id: 17, row: 'ta', rowName: 'た行', romanic: 'chi', hiragana: 'ち', katakana: 'チ', time: 36.20 },
    { id: 18, row: 'ta', rowName: 'た行', romanic: 'tu/tsu', hiragana: 'つ', katakana: 'ツ', time: 37.33 },
    { id: 19, row: 'ta', rowName: 'た行', romanic: 'te', hiragana: 'て', katakana: 'テ', time: 38.70 },
    { id: 20, row: 'ta', rowName: 'た行', romanic: 'to', hiragana: 'と', katakana: 'ト', time: 40.00 },
    { id: 21, row: 'na', rowName: 'な行', romanic: 'na', hiragana: 'な', katakana: 'ナ', time: 42.00 },
    { id: 22, row: 'na', rowName: 'な行', romanic: 'ni', hiragana: 'に', katakana: 'ニ', time: 43.00 },
    { id: 23, row: 'na', rowName: 'な行', romanic: 'nu', hiragana: 'ぬ', katakana: 'ヌ', time: 44.35 },
    { id: 24, row: 'na', rowName: 'な行', romanic: 'ne', hiragana: 'ね', katakana: 'ネ', time: 45.85 },
    { id: 25, row: 'na', rowName: 'な行', romanic: 'no', hiragana: 'の', katakana: 'ノ', time: 47.00 },
    { id: 26, row: 'ha', rowName: 'は行', romanic: 'ha', hiragana: 'は', katakana: 'ハ', time: 49.00 },
    { id: 27, row: 'ha', rowName: 'は行', romanic: 'hi', hiragana: 'ひ', katakana: 'ヒ', time: 50.40 },
    { id: 28, row: 'ha', rowName: 'は行', romanic: 'fu', hiragana: 'ふ', katakana: 'フ', time: 51.50 },
    { id: 29, row: 'ha', rowName: 'は行', romanic: 'he', hiragana: 'へ', katakana: 'ヘ', time: 52.50 },
    { id: 30, row: 'ha', rowName: 'は行', romanic: 'ho', hiragana: 'ほ', katakana: 'ホ', time: 54.00 },
    { id: 31, row: 'ma', rowName: 'ま行', romanic: 'ma', hiragana: 'ま', katakana: 'マ', time: 55.85 },
    { id: 32, row: 'ma', rowName: 'ま行', romanic: 'mi', hiragana: 'み', katakana: 'ミ', time: 57.00 },
    { id: 33, row: 'ma', rowName: 'ま行', romanic: 'mu', hiragana: 'む', katakana: 'ム', time: 58.00 },
    { id: 34, row: 'ma', rowName: 'ま行', romanic: 'me', hiragana: 'め', katakana: 'メ', time: 59.50 },
    { id: 35, row: 'ma', rowName: 'ま行', romanic: 'mo', hiragana: 'も', katakana: 'モ', time: 60.50 },
    { id: 36, row: 'ya', rowName: 'や行', romanic: 'ya', hiragana: 'や', katakana: 'ヤ', time: 62.00 },
    { id: 37, row: 'ya', rowName: 'や行', romanic: 'i', hiragana: 'い', katakana: 'イ', time: 63.30 },
    { id: 38, row: 'ya', rowName: 'や行', romanic: 'yu', hiragana: 'ゆ', katakana: 'ユ', time: 64.50 },
    { id: 39, row: 'ya', rowName: 'や行', romanic: 'e', hiragana: 'え', katakana: 'エ', time: 65.80 },
    { id: 40, row: 'ya', rowName: 'や行', romanic: 'yo', hiragana: 'よ', katakana: 'ヨ', time: 67.00 },
    { id: 41, row: 'ra', rowName: 'ら行', romanic: 'ra', hiragana: 'ら', katakana: 'ラ', time: 68.88 },
    { id: 42, row: 'ra', rowName: 'ら行', romanic: 'ri', hiragana: 'り', katakana: 'リ', time: 70.00 },
    { id: 43, row: 'ra', rowName: 'ら行', romanic: 'ru', hiragana: 'る', katakana: 'ル', time: 71.00 },
    { id: 44, row: 'ra', rowName: 'ら行', romanic: 're', hiragana: 'れ', katakana: 'レ', time: 72.00 },
    { id: 45, row: 'ra', rowName: 'ら行', romanic: 'ro', hiragana: 'ろ', katakana: 'ロ', time: 73.50 },
    { id: 46, row: 'wa', rowName: 'わ行', romanic: 'wa', hiragana: 'わ', katakana: 'ワ', time: 75.30 },
    { id: 47, row: 'wa', rowName: 'わ行', romanic: 'i', hiragana: 'い', katakana: 'イ', time: 76.20 },
    { id: 48, row: 'wa', rowName: 'わ行', romanic: 'u', hiragana: 'う', katakana: 'ウ', time: 77.30 },
    { id: 49, row: 'wa', rowName: 'わ行', romanic: 'e', hiragana: 'え', katakana: 'エ', time: 78.45 },
    { id: 50, row: 'wa', rowName: 'わ行', romanic: 'wo', hiragana: 'を', katakana: 'ヲ', time: 79.70 },
    { id: 51, row: 'n', rowName: 'n行', romanic: 'nn', hiragana: 'ん', katakana: 'ン', time: 81.00 },
    { id: 52, row: 'ga', rowName: 'が行', romanic: 'ga', hiragana: 'が', katakana: 'ガ' },
    { id: 53, row: 'ga', rowName: 'が行', romanic: 'gi', hiragana: 'ぎ', katakana: 'ギ' },
    { id: 54, row: 'ga', rowName: 'が行', romanic: 'gu', hiragana: 'ぐ', katakana: 'グ' },
    { id: 55, row: 'ga', rowName: 'が行', romanic: 'ge', hiragana: 'げ', katakana: 'ゲ' },
    { id: 56, row: 'ga', rowName: 'が行', romanic: 'go', hiragana: 'ご', katakana: 'ゴ' },
    { id: 57, row: 'za', rowName: 'ざ行', romanic: 'za', hiragana: 'ざ', katakana: 'ザ' },
    { id: 58, row: 'za', rowName: 'ざ行', romanic: 'ji', hiragana: 'じ', katakana: 'ジ' },
    { id: 59, row: 'za', rowName: 'ざ行', romanic: 'zu', hiragana: 'ず', katakana: 'ズ' },
    { id: 60, row: 'za', rowName: 'ざ行', romanic: 'ze', hiragana: 'ぜ', katakana: 'ゼ' },
    { id: 61, row: 'za', rowName: 'ざ行', romanic: 'zo', hiragana: 'ぞ', katakana: 'ゾ' },
    { id: 62, row: 'da', rowName: 'だ行', romanic: 'da', hiragana: 'だ', katakana: 'ダ' },
    { id: 63, row: 'da', rowName: 'だ行', romanic: 'ji', hiragana: 'ぢ', katakana: 'ヂ' },
    { id: 64, row: 'da', rowName: 'だ行', romanic: 'zu', hiragana: 'づ', katakana: 'ヅ' },
    { id: 65, row: 'da', rowName: 'だ行', romanic: 'de', hiragana: 'で', katakana: 'デ' },
    { id: 66, row: 'da', rowName: 'だ行', romanic: 'do', hiragana: 'ど', katakana: 'ド' },
    { id: 67, row: 'ba', rowName: 'ば行', romanic: 'ba', hiragana: 'ば', katakana: 'バ' },
    { id: 68, row: 'ba', rowName: 'ば行', romanic: 'bi', hiragana: 'び', katakana: 'ビ' },
    { id: 69, row: 'ba', rowName: 'ば行', romanic: 'bu', hiragana: 'ぶ', katakana: 'ブ' },
    { id: 70, row: 'ba', rowName: 'ば行', romanic: 'be', hiragana: 'べ', katakana: 'ベ' },
    { id: 71, row: 'ba', rowName: 'ば行', romanic: 'bo', hiragana: 'ぼ', katakana: 'ボ' },
    { id: 72, row: 'pa', rowName: 'ぱ行', romanic: 'pa', hiragana: 'ぱ', katakana: 'パ' },
    { id: 73, row: 'pa', rowName: 'ぱ行', romanic: 'pi', hiragana: 'ぴ', katakana: 'ピ' },
    { id: 74, row: 'pa', rowName: 'ぱ行', romanic: 'pu', hiragana: 'ぷ', katakana: 'プ' },
    { id: 75, row: 'pa', rowName: 'ぱ行', romanic: 'pe', hiragana: 'ぺ', katakana: 'ペ' },
    { id: 76, row: 'pa', rowName: 'ぱ行', romanic: 'po', hiragana: 'ぽ', katakana: 'ポ' }
]
